---
title: "R for HMIS Admins"
author: "Genelle Denzin"
date: "7/7/2020"
output: 
  ioslides_presentation:
    logo: COHHIOlogo_5.16.jpg
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
```

# Week 5: Turning you Loose

Presenter: Genelle Denzin (she/her)
(HMIS Data Analyst, a co-organizer of Columbus R-Ladies)

Co-presenter: Carolyn Hoffman (fellow R user, Training & Technical Assistance)

## Logistics

- No demo today!

- Please send questions/comments to the chat or raise your hand if you need to ask a question and I can unmute you. 

- I'm going to leave the readme at the GitHub link up as a resource, links to recordings, homework instructions, etc. 

- We're going to talk about where you can find help going forward!

## The R Community landscape

A little tension between base R crowd and RStudio crowd but mostly everyone agrees to live and let live. Use what makes you and your co-developers happy.

R is free and open source. It's maintained by developers who know and care about the language and its future and who are generally not paid for their work. There's a dynamic where often this arrangement becomes unsustainable. 

RStudio is a B Corp, and maintains the Tidyverse and shinyapps.io and a number of server products. They also contribute a lot to the maintenance of R as a language.

## How do I get help if I have an issue?

Continuum of effort, ascending order:

1. In the console, type `?mutate`, read the R documentation.
2. In the console, type `vignette("dplyr")` (or another package)
3. Google (you will often find your answer on StackOverflow!)
    * Paste error message
    * Search package name and problem
4. Slack (your local R-Ladies or the HMIS Help Slack #r-learners channel)
5. Ask a question on [RStudio Community](https://community.rstudio.com/)
6. Ask a question on StackOverflow (I've never had to do this)

## What if I Need to Ask for Help

* Follow guidelines of whatever site you are posting to. Most sites have a template and a series of questions to ask yourself before posting. 

* Include information about what you've tried, be clear about what exactly you are expecting the code to do, include the exact error message, etc.

* If applicable, always create a reproducible example of your problem for whoever is going to try to help you wherever possible. Get to know the reprex package!

## Toward better Reproducibility in HMIS

### For best reproducibility:

* As raw as possible coming out of HMIS (data structure already documented!)

* Data shaping in R (documented with Git)

* Data visualization in R (also documented with Git)

## Toward better Reproducibility in HMIS

### For decent level of reproducibility:

* As raw as possible coming out of HMIS (data structure already documented)

* Data shaping in R (documented with Git)

* Data visualization in a data visualization software such as Tableau or PowerBI (documentation not available or not shared)

## Toward better Reproducibility in HMIS

### Lowest level of reproducibility:

* Data comes from a custom report in your HMIS for which you have no documentation, or the documentation is often out of date

* This data gets massaged in some way in Excel (and these steps are not documented)

* Data goes into a data visualization software such as Tableau or PowerBI and the documentation for what is happening in that process is also not documented

## How do you build data visualizations in R?

* ggplot2
* [Leaflet](https://rstudio.github.io/leaflet/) package (interactive maps)
* [DataTable](https://rstudio.github.io/leaflet/) (DT package) (interactive and VERY controllable tables)
* Shiny: check out the [Shiny Gallery](https://shiny.rstudio.com/gallery/)
* [Plotly](https://plotly.com/r/) (interactive plots)
* Check out the [R Graph Gallery](https://www.r-graph-gallery.com/)

## How do you make data visualizations in R available?

* Shiny (shinyapps.io)
* R Markdown outputs (html, Word, slides, pdf)
* Bookdown (can write and publish a book to bookdown.org)
* Blogdown (can create and maintain a website/blog to any web server)
* RPubs (easy web publishing from R)

## How do you get a dataset OUT of your project directory?

Symbolic links! (One-time setup)

On Windows, you have to run your command prompt as an administrator.

I wrote a script to help me write the command, but it's basically:

`mklink "where you want it to go" "where it is"`

## What did this training series NOT cover that I should look into?

* Functions!
* Working with dates (Lubridate package)
* Building cool plots (ggplot2, plotly)

## What is Cool????

- Jesse Dirkman (Institute for Community Alliances)
- Genelle Denzin (COHHIO)
- Carolyn Hoffman (COHHIO)
- 

## IF YOU ARE SO INCLINED

- Donations to COHHIO's Pandemic Fund which helps organizations in Ohio keep our homeless neighbors safe from COVID-19. https://actionnetwork.org/fundraising/cohhio-pandemic-emergency-fund

- Donations to the Columbus Freedom Fund which bails out local Black Lives Matter protesters can be made here: https://www.paypal.me/columbusfreedomfund

# Off ya go!

